CREATE TABLE houses (
    id                       CHAR(36)      NOT NULL PRIMARY KEY,
    user_id                  CHAR(36)      NOT NULL,
    address_road_address     VARCHAR(255)  NULL,
    address_jibun_address    VARCHAR(255)  NULL,
    address_zonecode         VARCHAR(10)   NULL,
    address_latitude         DECIMAL(10,7) NULL,
    address_longitude        DECIMAL(10,7) NULL,
    address_detail           VARCHAR(255)  NULL,
    deal_type          VARCHAR(20)  NOT NULL,
    deposit            INT          NOT NULL DEFAULT 0,
    rent               INT          NOT NULL DEFAULT 0,
    maintenance_fee    INT          NULL,
    area               DECIMAL(7,2) NULL,
    built_year         INT          NULL,
    floor              INT          NULL,
    total_floor        INT          NULL,
    available_from     DATE         NULL,
    station_distance   INT          NULL,
    rooms              INT          NULL,
    bathrooms          INT          NULL,
    has_balcony        TINYINT(1)   NULL,
    has_elevator       TINYINT(1)   NULL,
    has_parking        TINYINT(1)   NULL,
    options_json       JSON         NULL,
    security_json      JSON         NULL,
    garbage            VARCHAR(255) NULL,
    water_pressure     TINYINT      NULL,
    sunlight           TINYINT      NULL,
    noise              TINYINT      NULL,
    insulation         TINYINT      NULL,
    ventilation        TINYINT      NULL,
    moisture           TINYINT      NULL,
    neighborhood       TINYINT      NULL,
    first_impression   TINYINT      NULL,
    memo               TEXT         NULL,
    created_at         DATETIME(3)  NOT NULL,
    updated_at         DATETIME(3)  NOT NULL,
    deleted_at         DATETIME(3)  NULL,
    KEY ix_houses_user (user_id),
    KEY ix_houses_user_deleted (user_id, deleted_at),
    CONSTRAINT fk_houses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
