CREATE TABLE residences (
    id                       CHAR(36)     NOT NULL PRIMARY KEY,
    user_id                  CHAR(36)     NOT NULL,
    source_house_id          CHAR(36)     NULL,
    name                     VARCHAR(100) NOT NULL,
    era_label                VARCHAR(100) NULL,
    is_favorite              TINYINT(1)   NOT NULL DEFAULT 0,
    address_road_address     VARCHAR(255) NULL,
    address_jibun_address    VARCHAR(255) NULL,
    address_zonecode         VARCHAR(10)  NULL,
    address_latitude         DECIMAL(10,7) NULL,
    address_longitude        DECIMAL(10,7) NULL,
    address_detail           VARCHAR(255) NULL,
    deal_type                VARCHAR(20)  NULL,
    deposit                  INT          NULL,
    rent                     INT          NULL,
    maintenance_fee          INT          NULL,
    area                     DECIMAL(7,2) NULL,
    built_year               INT          NULL,
    floor                    INT          NULL,
    total_floor              INT          NULL,
    rooms                    INT          NULL,
    bathrooms                INT          NULL,
    has_balcony              TINYINT(1)   NULL,
    has_elevator             TINYINT(1)   NULL,
    has_parking              TINYINT(1)   NULL,
    options_json             JSON         NULL,
    security_json            JSON         NULL,
    garbage                  VARCHAR(255) NULL,
    water_pressure           TINYINT      NULL,
    sunlight                 TINYINT      NULL,
    noise                    TINYINT      NULL,
    insulation               TINYINT      NULL,
    ventilation              TINYINT      NULL,
    moisture                 TINYINT      NULL,
    neighborhood             TINYINT      NULL,
    first_impression         TINYINT      NULL,
    memo                     TEXT         NULL,
    contract_start_date      DATE         NOT NULL,
    contract_end_date        DATE         NOT NULL,
    landlord_memo            TEXT         NULL,
    is_current               TINYINT(1)   NOT NULL DEFAULT 0,
    move_in_photo_ids_json   JSON         NULL,
    contract_photo_id        CHAR(36)     NULL,
    meter_electricity        INT          NULL,
    meter_water              INT          NULL,
    meter_gas                INT          NULL,
    meter_recorded_at        DATE         NULL,
    created_at               DATETIME(3)  NOT NULL,
    updated_at               DATETIME(3)  NOT NULL,
    deleted_at               DATETIME(3)  NULL,
    KEY ix_residences_user (user_id),
    KEY ix_residences_user_deleted (user_id, deleted_at),
    KEY ix_residences_source (source_house_id),
    CONSTRAINT fk_residences_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_residences_house FOREIGN KEY (source_house_id) REFERENCES houses(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
